### ISSUE TITLE
Problems with clear ember app

### ISSUE THREAD

**Issue by hugoruscitti** [philipbjorge/ember-cli-typescript#17]
Hi, i have an issue with ember-cli 1.13. It's any step i'm missing, i must create a tsconfig.json before launch ember serve?

this is the error i get:

```
$ ember s
version: 1.13.8
Cannot load tsconfig.json from [object Object]: ts.parseConfigFileText is not a function
Error: Cannot load tsconfig.json from [object Object]: ts.parseConfigFileText is not a function
    at parseOptions (/Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli-typescript-compiler/node_modules/broccoli-typescript-compiler/index.js:44:11)
    at new TypeScript (/Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli-typescript-compiler/node_modules/broccoli-typescript-compiler/index.js:55:18)
    at TypeScriptPreprocessor.toTree (/Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli-typescript-compiler/lib/typescript-preprocessor.js:10:10)
    at /Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:26
    at Array.forEach (native)
    at processPlugins (/Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:11)
    at module.exports.preprocessJs (/Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:177:10)
    at EmberApp.appAndDependencies (/Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli/lib/broccoli/ember-app.js:907:25)
    at EmberApp.javascript (/Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli/lib/broccoli/ember-app.js:973:34)
    at EmberApp.toArray (/Users/hugoruscitti/proyectos/spectro/spectro-web-commands/node_modules/ember-cli/lib/broccoli/ember-app.js:1346:10)
```

**Comment by choclaudio** [comment]
Install typescript around 1.6 in your own app. Then I also found some code issues in the broccoli-typescript version in ember-cli-typescript-compiler. I ended up fixing those issues just to find that the broccoli repo had already the fixes in later versions.

this is actually part of (if not all depending on your setup) your issue:
https://github.com/philipbjorge/ember-cli-typescript-compiler/issues/16
